name: Remote Update

on:
  workflow_dispatch:
    inputs:
      files_json:
        description: >
          JSON: {"index.html":"<base64>", "styles.css":"<base64>", ...}
        required: true
      commit_message:
        description: Сообщение коммита
        required: false
        default: "remote update"
      branch:
        description: Ветка для коммита (например, main)
        required: false
        default: "main"

# Даем боту права на запись и на PR
permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Применить файлы из JSON (base64 → файлы)
        run: |
          echo '${{ github.event.inputs.files_json }}' > payload.json
          node - <<'NODE'
          const fs = require('fs');
          const path = require('path');
          const raw = fs.readFileSync('payload.json','utf8').trim();
          let data;
          try { data = JSON.parse(raw); } catch(e) {
            console.error('Bad JSON:', e.message); process.exit(1);
          }
          const keys = Object.keys(data || {});
          if (!keys.length) { console.log('Нет файлов'); process.exit(0); }
          for (const p of keys) {
            const b64 = data[p];
            if (typeof b64 !== 'string') { console.warn('skip:', p); continue; }
            fs.mkdirSync(path.dirname(p), { recursive: true });
            fs.writeFileSync(p, Buffer.from(b64, 'base64'));
            console.log('Wrote', p);
          }
          NODE

      - name: Commit (local)
        id: commit
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes"
            exit 0
          fi
          git commit -m "${{ github.event.inputs.commit_message }}"
          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Push to target branch
        id: push
        if: steps.commit.outputs.changed == 'true'
        run: |
          set +e
          git push origin HEAD:${{ github.event.inputs.branch }}
          status=$?
          echo "status=$status" >> $GITHUB_OUTPUT
          if [ $status -ne 0 ]; then
            echo "direct_push_failed=true" >> $GITHUB_OUTPUT
          else
            echo "direct_push_failed=false" >> $GITHUB_OUTPUT
          fi

      # Если main защищен и пуш не прошел — создаем ветку и PR
      - name: Fallback: create PR
        if: steps.push.outputs.direct_push_failed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ github.event.inputs.commit_message }}
          title: "Remote update: ${{ github.event.inputs.commit_message }}"
          body: "Авто-PR от workflow Remote Update"
          base: ${{ github.event.inputs.branch }}
          branch: remote-update/${{ github.run_id }}
