name: Remote Update

on:
  workflow_dispatch:
    inputs:
      files_json:
        description: >
          JSON: {"index.html":"<base64>", "styles.css":"<base64>", ...}
        required: true
      commit_message:
        description: Сообщение коммита
        required: false
        default: "remote update"
      branch:
        description: Ветка для коммита (например, main)
        required: false
        default: "main"

# ВАЖНО: даём Action права на запись и создание PR
permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Save payload.json
        shell: bash
        run: |
          cat > payload.json <<'EOF'
          ${{ github.event.inputs.files_json }}
          EOF
          echo "Payload length: $(wc -c < payload.json) bytes"

      - name: Decode base64 files from payload.json
        shell: node
        run: |
          const fs = require('fs');
          const path = require('path');
          const raw = fs.readFileSync('payload.json','utf8').trim();
          if (!raw) { throw new Error('payload.json пуст'); }
          let data;
          try { data = JSON.parse(raw); }
          catch(e){ throw new Error('Неверный JSON: '+e.message); }
          const keys = Object.keys(data||{});
          if (!keys.length) { console.log('Нет файлов для применения'); process.exit(0); }
          for (const p of keys) {
            const b64 = data[p];
            if (typeof b64 !== 'string') { console.log('skip (not string):', p); continue; }
            fs.mkdirSync(path.dirname(p), { recursive: true });
            fs.writeFileSync(p, Buffer.from(b64, 'base64'));
            console.log('Wrote', p);
          }

      - name: Git commit
        id: commit
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "${{ github.event.inputs.commit_message }}"
          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Push directly
        id: push
        if: steps.commit.outputs.changed == 'true'
        shell: bash
        run: |
          set +e
          git push origin HEAD:${{ github.event.inputs.branch }}
          code=$?
          echo "status=$code" >> $GITHUB_OUTPUT
          if [ $code -ne 0 ]; then
            echo "direct_push_failed=true" >> $GITHUB_OUTPUT
          else
            echo "direct_push_failed=false" >> $GITHUB_OUTPUT
          fi

      - name: Open Pull Request (fallback if branch protected)
        if: steps.push.outputs.direct_push_failed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: ${{ github.event.inputs.commit_message }}
          title: "Remote update: ${{ github.event.inputs.commit_message }}"
          body: "Авто-PR от workflow Remote Update"
          base: ${{ github.event.inputs.branch }}
          branch: remote-update/${{ github.run_id }}
